package com.myspace.sss;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class cfefe implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public cfefe() {
    }




}