package com.myspace.sss;

/**
 * This class was automatically generated by the data modeler tool. feeff
 */

public class fdgfe implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String vfdv;

	public fdgfe() {
	}

	public java.lang.String getVfdv() {
		return this.vfdv;
	}

	public void setVfdv(java.lang.String vfdv) {
		this.vfdv = vfdv;
	}

	public fdgfe(java.lang.String vfdv) {
		this.vfdv = vfdv;
	}

}